const MusicActionTypes = {
    LIST_MUSIC: 'LIST_MUSIC',
    HIDDEN: 'HIDDEN',
    MUSIC_LOVE: 'MUSIC_LOVE',
    SET_NULL: 'SET_NULL',
    GET_PLAY_LIST: 'GET_PLAY_LIST',
    ADD_MUSIC_PLAY: 'ADD_MUSIC_PLAY',
    ADD_PLAY_LIST: 'ADD_PLAY_LIST',
    PLAY_MUSIC_LOVE: 'PLAY_MUSIC_LOVE',
    REMOVE_MUSIC_LOVE: 'REMOVE_MUSIC_LOVE',
    LIST_TOP_MUSIC: 'LIST_TOP_MUSIC',
    RANDOM_MUSIC: 'RANDOM_MUSIC',
    ADD_ONE_MUSIC:'ADD_ONE_MUSIC',
    IS_PLAY:'IS_PLAY'
  };
  
  export default MusicActionTypes;